# Rol que crea imagen personalizada de NGINX y sube al ACR
- name: Crear imagen personalizada y subir al ACR
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars_files:
   - vault_vars.yml
  roles:
   - nginx_image
  tags: 
   - crear_imagen

# Rol que despliega la imagen subida desde ACR a un contenedor Podman
- name: Despliegue de contenedor Nginx desde ACR
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars_files:
   - vault_vars.yml
  roles:
   - nginx
  tags: 
   - desplegar
  
# Rol que sube imágenes Richie a Docker a ACR
- name: Subir imágenes Richie a DockerHub a ACR
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
   - vault_vars.yml
   - roles/richie_image_transfer/vars/main.yml
  roles:
   - richie_image_transfer
  tags: 
   - subir_imagenes
 